
- hosts: vagrants
  become: yes
  tasks:
    - name: uname -r
      shell: uname -r | sed -e 's/generic/virtual/'
      register: kernel_release

    - name: apt-get install packages
      apt:
        pkg: '{{ item }}'
        state: present
        update_cache: yes
      with_items:
        - linux-image-extra-{{ kernel_release.stdout }}
        - linux-image-extra-virtual

    - name: apt-get install packages
      apt:
        pkg: '{{ item }}'
        state: present
        update_cache: yes
      with_items:
        - apt-file
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python-software-properties
    
    - name: apt-file update
      shell: apt-file update && apt-file search add-apt-repository

    - name: Add Docker's official GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    - shell: apt-key fingerprint 0EBFCD88

    - name: distribution-specific information
      shell: lsb_release -cs
      register: lsb_release

    - name: Add repository
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"

    - name: install docker-ce
      apt:
        pkg: '{{ item }}'
        state: present
        update_cache: yes
      with_items:
        - docker-ce
